INSERT INTO certify.credential_config (
    credential_config_key_id, config_id, status, vc_template, doctype, sd_jwt_vct,
    context, credential_type, credential_format, did_url, key_manager_app_id,
    key_manager_ref_id, signature_algo, signature_crypto_suite, sd_claim, display,
    display_order, scope, cryptographic_binding_methods_supported,
    credential_signing_alg_values_supported, proof_types_supported, credential_subject,
    mso_mdoc_claims, plugin_configurations, credential_status_purpose, qr_settings,
    qr_signature_algo, cr_dtimes, upd_dtimes
) VALUES (
    'OpenG2PBeneficiaryCredential',
    gen_random_uuid()::VARCHAR(255),
    'active',
    'ewogICJAY29udGV4dCI6IFsKICAgICJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSIsCiAgICB7CiAgICAgICJPcGVuRzJQQmVuZWZpY2lhcnlDcmVkZW50aWFsIjogImh0dHBzOi8vb3BlbmcycC5vcmcvbnMjT3BlbkcyUEJlbmVmaWNpYXJ5Q3JlZGVudGlhbCIsCiAgICAgICJmdW5jdGlvbmFsUmVjb3JkSWQiOiAiaHR0cHM6Ly9zY2hlbWEub3JnL2lkZW50aWZpZXIiLAogICAgICAiZnVsbE5hbWUiOiAiaHR0cHM6Ly9zY2hlbWEub3JnL25hbWUiLAogICAgICAiZGF0ZU9mQmlydGgiOiAiaHR0cHM6Ly9zY2hlbWEub3JnL2JpcnRoRGF0ZSIKICAgIH0sCiAgICAiaHR0cHM6Ly93M2lkLm9yZy9zZWN1cml0eS9zdWl0ZXMvZWQyNTUxOS0yMDIwL3YxIgogIF0sCiAgImlzc3VlciI6ICIke19pc3N1ZXJ9IiwKICAidHlwZSI6IFsKICAgICJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsCiAgICAiT3BlbkcyUEJlbmVmaWNpYXJ5Q3JlZGVudGlhbCIKICBdLAogICJpc3N1YW5jZURhdGUiOiAiJHt2YWxpZEZyb219IiwKICAiZXhwaXJhdGlvbkRhdGUiOiAiJHt2YWxpZFVudGlsfSIsCiAgImNyZWRlbnRpYWxTdWJqZWN0IjogewogICAgImlkIjogIiR7X2hvbGRlcklkfSIsCiAgICAiZnVuY3Rpb25hbFJlY29yZElkIjogIiR7ZnVuY3Rpb25hbFJlY29yZElkfSIsCiAgICAiZnVsbE5hbWUiOiAiJHtmdWxsTmFtZX0iLAogICAgImRhdGVPZkJpcnRoIjogIiR7ZGF0ZU9mQmlydGh9IgogIH0KfQ==',
    NULL,
    NULL,
    'https://www.w3.org/2018/credentials/v1',
    'OpenG2PBeneficiaryCredential,VerifiableCredential',
    'ldp_vc',
    'did:web:8398-2405-201-1029-3025-e142-9ad3-e1f2-f543.ngrok-free.app',
    'CERTIFY_VC_SIGN_ED25519',
    'ED25519_SIGN',
    'EdDSA',
    'Ed25519Signature2020',
    NULL,
    '[{"name": "OpenG2P Beneficiary Credential", "locale": "en", "logo": {"url": "https://mosip.github.io/inji-config/logos/agro-vertias-logo.png", "alt_text": "OpenG2P Logo"}, "background_color": "#0b6e4f", "text_color": "#FFFFFF"}]'::JSONB,
    ARRAY['functionalRecordId', 'fullName', 'dateOfBirth'],
    'openg2p_beneficiary_vc_ldp',
    ARRAY['did:jwk'],
    ARRAY['Ed25519Signature2020'],
    '{"jwt": {"proof_signing_alg_values_supported": ["RS256", "ES256"]}}'::JSONB,
    '{"functionalRecordId": {"display": [{"name": "Functional Record ID", "locale": "en"}]}, "fullName": {"display": [{"name": "Full Name", "locale": "en"}]}, "dateOfBirth": {"display": [{"name": "Date of Birth", "locale": "en"}]}}'::JSONB,
    NULL,
    NULL,
    NULL,
    '[{"Full Name": "${fullName}", "Functional ID": "${functionalRecordId}", "Date Of Birth": "${dateOfBirth}"}]'::JSONB,
    'EdDSA',
    NOW(),
    NULL
);
