{{- if and .Values.verifyService.enabled .Values.verifyService.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "verify.serviceAccountName" . }}
  labels: {{- include "verify.labels" . | nindent 4 }}
{{- end }}
